### ISSUE TITLE
Releasing SDXL version? 

### ISSUE THREAD

**Issue by alnaeini** [wfanyue/DPG-T2I-Personalization#1]
Any plan on releasing training with SDXL?

**Comment by wfanyue** [comment]
Hi, Thanks for your interest in our work. We do not conduct experiments with SDXL baseline. But the implementation of the reward model used in our method is simple, you can refer to train_dreambooth_dpg.py and modify the pre-trained model to SDXL. If you have any questions, feel free to contact me.

**Comment by alnaeini** [comment]
Thanks
